universe   = vanilla
getenv     = True
executable = sub_skim.sh
+JobFlavour           = "tomorrow"
requirements = (OpSysAndVer =?= "CentOS7")
RequestCpus = 8

log        = cond/MBPD1pgoing.log
output     = cond/MBPD1pgoing.out
error      = cond/MBPD1pgoing.err
arguments = DATA_SAMPLES/MB/pgoing/MB_PD1_pgoing.txt DATA_SAMPLES/MB/pgoing/V0_MB_PD1_pgoing.txt /eos/user/e/eprifti/JetV0_skims/Data/MB_PD1_pgoing_skim.root 0
queue

log        = cond/MBPD2pgoing.log
output     = cond/MBPD2pgoing.out
error      = cond/MBPD2pgoing.err
arguments = DATA_SAMPLES/MB/pgoing/MB_PD2_pgoing.txt DATA_SAMPLES/MB/pgoing/V0_MB_PD2_pgoing.txt /eos/user/e/eprifti/JetV0_skims/Data/MB_PD2_pgoing_skim.root 0
queue

log        = cond/MBPD3pgoing.log
output     = cond/MBPD3pgoing.out
error      = cond/MBPD3pgoing.err
arguments = DATA_SAMPLES/MB/pgoing/MB_PD3_pgoing.txt DATA_SAMPLES/MB/pgoing/V0_MB_PD3_pgoing.txt /eos/user/e/eprifti/JetV0_skims/Data/MB_PD3_pgoing_skim.root 0
queue

log        = cond/MBPD4pgoing.log
output     = cond/MBPD4pgoing.out
error      = cond/MBPD4pgoing.err
arguments = DATA_SAMPLES/MB/pgoing/MB_PD4_pgoing.txt DATA_SAMPLES/MB/pgoing/V0_MB_PD4_pgoing.txt /eos/user/e/eprifti/JetV0_skims/Data/MB_PD4_pgoing_skim.root 0
queue

log        = cond/MBPD5pgoing.log
output     = cond/MBPD5pgoing.out
error      = cond/MBPD5pgoing.err
arguments = DATA_SAMPLES/MB/pgoing/MB_PD5_pgoing.txt DATA_SAMPLES/MB/pgoing/V0_MB_PD5_pgoing.txt /eos/user/e/eprifti/JetV0_skims/Data/MB_PD5_pgoing_skim.root 0
queue

log        = cond/MBPD6pgoing.log
output     = cond/MBPD6pgoing.out
error      = cond/MBPD6pgoing.err
arguments = DATA_SAMPLES/MB/pgoing/MB_PD6_pgoing.txt DATA_SAMPLES/MB/pgoing/V0_MB_PD6_pgoing.txt /eos/user/e/eprifti/JetV0_skims/Data/MB_PD6_pgoing_skim.root 0
queue

log        = cond/MBPD7pgoing.log
output     = cond/MBPD7pgoing.out
error      = cond/MBPD7pgoing.err
arguments = DATA_SAMPLES/MB/pgoing/MB_PD7_pgoing.txt DATA_SAMPLES/MB/pgoing/V0_MB_PD7_pgoing.txt /eos/user/e/eprifti/JetV0_skims/Data/MB_PD7_pgoing_skim.root 0
queue

log        = cond/MBPD8pgoing.log
output     = cond/MBPD8pgoing.out
error      = cond/MBPD8pgoing.err
arguments = DATA_SAMPLES/MB/pgoing/MB_PD8_pgoing.txt DATA_SAMPLES/MB/pgoing/V0_MB_PD8_pgoing.txt /eos/user/e/eprifti/JetV0_skims/Data/MB_PD8_pgoing_skim.root 0
queue

